Exception: "<pending_xref py:class=\"SasTokenError\" py:module=\"azure.iot.hub.sastoken\"\
  \ refdoc=\"azure.iot.hub\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"Exception\"\
  \ reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py py-class\"\
  >\n        Exception\n"
object: "<pending_xref py:class=\"StatisticsOperations\" py:module=\"azure.iot.hub.protocol.operations.statistics_operations\"\
  \ refdoc=\"azure.iot.hub.protocol.operations\" refdomain=\"py\" refexplicit=\"False\"\
  \ reftarget=\"object\" reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"\
  xref py py-class\">\n        object\n"
